[project]
name = "Stacks Lab"
description = "Bitcoin Superapp on Stacks"
authors = []
telemetry = true
cache_dir = "./.cache"

# [[project.requirements]]
# contract_id = "ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.sbtc-token"
# Mainnet: SM3VDXK3WZZSA84XXFKAFAF15NNZX32CTSG82JFQ4.sbtc-token

[contracts.launchpad-v14]
path = "contracts/launchpad-v14.clar"
clarity_version = 2
epoch = '2.1'

[contracts.marketplace-v14]
path = "contracts/marketplace-v14.clar"
clarity_version = 2
epoch = '2.1'

[contracts.reputation-v14]
path = "contracts/reputation-v14.clar"
clarity_version = 2
epoch = '2.1'

[contracts.liquidity-locker-v14]
path = "contracts/liquidity-locker-v14.clar"
clarity_version = 2
epoch = '2.1'

[contracts.stacks-hub-avatars-v14]
path = "contracts/stacks-hub-avatars-v14.clar"
clarity_version = 2
epoch = '2.1'

[contracts.sip009-nft-trait-v14]
path = "contracts/sip009-nft-trait-v14.clar"
clarity_version = 2
epoch = '2.1'

[contracts.sip010-ft-trait-v14]
path = "contracts/sip010-ft-trait-v14.clar"
clarity_version = 2
epoch = '2.1'

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false


